config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

    resources :albums do
      resources :pictures
    end

  root 'home#index'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :pictures	
  has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
  paginates_per 2	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :album
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  paginates_per 1
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
  	@album = Album.new
  end

  def index
  	@album = Album.all.page params[:page]

  end

  def show

	  @album = Album.find(params[:id])
    @pictures = @album.pictures.page params[:page]
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(album_params)
 
  	if @album.save
  	  redirect_to @album
  	  else
        render 'new'
      end
  end

  def update
    @album = Album.find(params[:id])
 
    if @album.update(album_params)
      redirect_to @album
    else
      render 'edit'
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
 
    redirect_to albums_path
  end

  private
  	def album_params
      params.require(:album).permit(:title,:cover)
  	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.new
  end

  def create
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.create(picture_params)
    redirect_to album_path(@album)
  end

  def destroy
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.find(params[:id])
    @picture.destroy
 
    redirect_to album_path(@album)
  end
 
  private
    def picture_params
      params.require(:picture).permit(:title, :image,:tag_list)
    end	
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/albums/edit.html.erb
<h1>Edit album</h1>
 
  <%= form_with model:@album, local: true, html: { multipart: true } do  |form| %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p><br>

  <p>
    <%= form.file_field :cover %>
  </p>

  <%= submit_tag("update") %>
  <%= submit_tag("upload") %>

 
<% end %>

app/views/albums/index.html.erb
<h1>Albums</h1>
<%= link_to 'New Album',new_album_path %>

<h1>Listing albums</h1>
 
<table>
  <tr>
    <th>Title</th>
  </tr>
 
  <% @album.each do |album| %>
    <tr>
      <td><%= image_tag album.cover.url %></td>
      <td><%= album.title %></td>
      <td><%= link_to 'Show', album_path(album) %></td>
      <td><%= link_to 'Edit', edit_album_path(album) %></td>
      <td><%= link_to 'Destroy', album_path(album),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= paginate @album %>

app/views/albums/new.html.erb
<%= form_with model:@album, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <%= submit_tag("Create") %>
<% end %>

app/views/albums/show.html.erb
<p>
  <%= image_tag @album.cover.url %>	
  <strong>Title:</strong>
  <%= @album.title %>
  <%= link_to 'Create New Picture',new_album_picture_path(@album)%><br>

  <table>
  	<tr>
      <th><h2>Pictures</h2></th>
    </tr>

    <% @pictures.each do |picture| %>
    <tr>
      <td><%= image_tag picture.image.url %></td>
      <td><%= link_to 'Destroy', album_picture_path(@album, picture),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
       
    </tr>
  <% end %>
  </table>
  
  <%= form_with scope: :picture, local: true do |form| %>
    <p>
      <%= form.label :Tag %><br>
      <%= form.text_field :title %>
    </p>
  <% end %>
  <%= paginate @pictures %>
  <%= link_to 'Back',albums_path(@album)%>
 
</p>

app/views/home/index.html.erb
<h1>Sign in or Sign up</h1>



<% if user_signed_in? %>
  
  <%= link_to('Sign out', destroy_user_session_path, :method => :delete) %>        
  
<% else %>
  
  <%= link_to('Sign in', new_user_session_path)  %> <br>
  <%= link_to 'Sign up', new_user_registration_path%> 
  
<% end %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PHOTOGALLERY</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/new.html.erb
<%= form_with scope: :picture, url: album_pictures_path(@album), local: true do |form| %>
 

  <p>
    <%= form.file_field :image %>
  </p>
 
  <%= submit_tag("Upload") %>
<% end %>